import client from './client'

export const list = () => client.get('/routers')
export const get = (id) => client.get(`/routers/${id}`)
export const create = (data) => client.post('/routers', data)
export const update = (id, data) => client.put(`/routers/${id}`, data)
export const remove = (id) => client.delete(`/routers/${id}`)
export const listInterfaces = (id) => client.get(`/routers/${id}/interfaces`)
export const addInterface = (id, data) => client.post(`/routers/${id}/interfaces`, data)
export const updateInterface = (routerId, interfaceId, data) => client.put(`/routers/${routerId}/interfaces/${interfaceId}`, data)
export const removeInterface = (routerId, interfaceId) => client.delete(`/routers/${routerId}/interfaces/${interfaceId}`)
export const getSnmpInfo = (id) => client.get(`/routers/${id}/snmp-info`)

export const listSnmpMonitors = (id) => client.get(`/routers/${id}/snmp-monitors`)
export const createSnmpMonitor = (id, data) => client.post(`/routers/${id}/snmp-monitors`, data)
export const updateSnmpMonitor = (id, mid, data) => client.put(`/routers/${id}/snmp-monitors/${mid}`, data)
export const deleteSnmpMonitor = (id, mid) => client.delete(`/routers/${id}/snmp-monitors/${mid}`)
export const getSnmpLatest = (id) => client.get(`/routers/${id}/snmp-latest`)
export const getSnmpMetrics = (id, params) => client.get(`/routers/${id}/snmp-metrics`, { params })
export const collectSnmpNow = (id) => client.post(`/routers/${id}/snmp-collect`)
export const discoverSnmp = (id) => client.get(`/routers/${id}/snmp-discover`)
export const copySnmpMonitors = (id, targetId) => client.post(`/routers/${id}/snmp-copy-to/${targetId}`)
export const cloneRouter = (id) => client.post(`/routers/${id}/clone`)

export const listWifiNetworks = (id) => client.get(`/routers/${id}/wifi-networks`)
export const createWifiNetwork = (id, data) => client.post(`/routers/${id}/wifi-networks`, data)
export const updateWifiNetwork = (id, wid, data) => client.put(`/routers/${id}/wifi-networks/${wid}`, data)
export const deleteWifiNetwork = (id, wid) => client.delete(`/routers/${id}/wifi-networks/${wid}`)
export const copyWifiNetworks = (id, targetId) => client.post(`/routers/${id}/wifi-networks/copy-to/${targetId}`)
